include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat true problems as errors
    missing_required_param: error
    missing_return: error
    dead_code: error
    invalid_use_of_visible_for_testing_member: error
    invalid_use_of_protected_member: error
    # Don't fail builds on stylistic nits
    lines_longer_than_80_chars: ignore
    avoid_print: ignore  # we use safeLog; prints in tests allowed
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - prefer_final_locals
    - unawaited_futures
    - avoid_slow_async_io
    - use_build_context_synchronously
    - prefer_single_quotes
    - prefer_relative_imports