include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - test/**/golden/**
    - test/**/**_golden_test.dart
    - test/**/golden_*.*
    - test_driver/**
    - integration_test/**
    - scripts/**
    - tool/**
    - lib/legacy/**
  errors:
    # Treat true problems as errors
    missing_required_param: error
    missing_return: error
    dead_code: error
    invalid_use_of_visible_for_testing_member: error
    invalid_use_of_protected_member: error
    # Don't fail builds on stylistic nits
    lines_longer_than_80_chars: ignore
    avoid_print: error
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_declare_return_types: true
    directives_ordering: true
    prefer_final_locals: true
    unawaited_futures: true
    avoid_slow_async_io: true
    use_build_context_synchronously: true
    prefer_single_quotes: true
    prefer_relative_imports: true