name: wedecor_enquiries
description: "WeDecor Enquiries Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.6.2
  firebase_messaging: ^15.2.10
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  firebase_app_check: ^0.3.2+10
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Routing
  go_router: ^14.8.1
  
  # Data Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # UI
  flutter_hooks: ^0.20.5
  flutter_slidable: ^3.1.2
  
  # Utils
  url_launcher: ^6.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true