// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Import our secure configuration
import 'package:we_decor_enquiries/core/config/firebase_config.dart';

/// Default Firebase configuration options for the current platform.
///
/// This class provides platform-specific Firebase configuration options
/// using secure environment variable handling instead of hardcoded API keys.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    // Using concrete values for the new web app in project wedecorenquries
    apiKey: 'AIzaSyCB1Zln4VM1fXtEoJSXIRzguxVPJAWV8ZI',
    appId: '1:747327664982:web:98e5e0d4bed9a1526edcf7',
    messagingSenderId: '747327664982',
    projectId: 'wedecorenquries',
    authDomain: 'wedecorenquries.firebaseapp.com',
    storageBucket: 'wedecorenquries.appspot.com',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: 'AIzaSyBrNRND3_O6Gavhd_a_FYP11ZpKbBGXgF4',
    appId: '1:747327664982:android:2b36161e30beb0cd6edcf7',
    messagingSenderId: '747327664982',
    projectId: 'wedecorenquries',
    storageBucket: 'wedecorenquries.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: FirebaseConfig.apiKey,
    appId: '1:270194759200:ios:add1c459e9abd7879cce45',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquries',
    storageBucket: 'wedecorenquries.appspot.com',
    iosBundleId: 'com.example.weDecorEnquiries',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: FirebaseConfig.apiKey,
    appId: '1:270194759200:ios:add1c459e9abd7879cce45',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquries',
    storageBucket: 'wedecorenquries.appspot.com',
    iosBundleId: 'com.example.weDecorEnquiries',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: FirebaseConfig.apiKey,
    appId: '1:270194759200:web:we_decor_enquiries',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquries',
    authDomain: 'wedecorenquries.firebaseapp.com',
    storageBucket: 'wedecorenquries.appspot.com',
  );
}
