// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2k0yFFJrEMY8A6YLyu9X_6RRGfSgT9tk',
    appId: '1:270194759200:web:we_decor_enquiries',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquiries',
    authDomain: 'wedecorenquiries.firebaseapp.com',
    storageBucket: 'wedecorenquiries.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2k0yFFJrEMY8A6YLyu9X_6RRGfSgT9tk',
    appId: '1:270194759200:android:add1c459e9abd7879cce45',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquiries',
    storageBucket: 'wedecorenquiries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9LDP8HHwWGzAb1e73xMXJoEAepQVrX4',
    appId: '1:270194759200:ios:0172993a81d51bf19cce45',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquiries',
    storageBucket: 'wedecorenquiries.firebasestorage.app',
    iosBundleId: 'com.example.weDecorEnquiries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9LDP8HHwWGzAb1e73xMXJoEAepQVrX4',
    appId: '1:270194759200:ios:0172993a81d51bf19cce45',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquiries',
    storageBucket: 'wedecorenquiries.firebasestorage.app',
    iosBundleId: 'com.example.weDecorEnquiries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2k0yFFJrEMY8A6YLyu9X_6RRGfSgT9tk',
    appId: '1:270194759200:web:we_decor_enquiries',
    messagingSenderId: '270194759200',
    projectId: 'wedecorenquiries',
    authDomain: 'wedecorenquiries.firebaseapp.com',
    storageBucket: 'wedecorenquiries.firebasestorage.app',
  );
} 