// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'enquiry.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$EnquiryImpl _$$EnquiryImplFromJson(Map<String, dynamic> json) => _$EnquiryImpl(
  id: json['id'] as String,
  customerName: json['customerName'] as String,
  customerEmail: json['customerEmail'] as String?,
  customerPhone: json['customerPhone'] as String?,
  eventType: json['eventTypeValue'] as String,
  eventTypeLabel: json['eventTypeLabel'] as String?,
  eventDate: DateTime.parse(json['eventDate'] as String),
  eventLocation: json['eventLocation'] as String?,
  guestCount: (json['guestCount'] as num?)?.toInt(),
  budgetRange: json['budgetRange'] as String?,
  description: json['description'] as String?,
  status: json['statusValue'] as String? ?? 'new',
  statusLabel: json['statusLabel'] as String?,
  paymentStatus: json['paymentStatusValue'] as String?,
  paymentStatusLabel: json['paymentStatusLabel'] as String?,
  totalCost: (json['totalCost'] as num?)?.toDouble(),
  advancePaid: (json['advancePaid'] as num?)?.toDouble(),
  assignedTo: json['assignedTo'] as String?,
  createdAt: DateTime.parse(json['createdAt'] as String),
  updatedAt: json['updatedAt'] == null ? null : DateTime.parse(json['updatedAt'] as String),
  createdBy: json['createdBy'] as String?,
  priority: json['priorityValue'] as String?,
  priorityLabel: json['priorityLabel'] as String?,
  source: json['sourceValue'] as String?,
  sourceLabel: json['sourceLabel'] as String?,
  notes: json['notes'] as String?,
  images: (json['images'] as List<dynamic>?)?.map((e) => e as String).toList() ?? const [],
  customerNameLower: json['customerNameLower'] as String?,
  phoneNormalized: json['phoneNormalized'] as String?,
  assigneeName: json['assigneeName'] as String?,
  createdByName: json['createdByName'] as String?,
  statusUpdatedAt: json['statusUpdatedAt'] == null
      ? null
      : DateTime.parse(json['statusUpdatedAt'] as String),
  statusUpdatedBy: json['statusUpdatedBy'] as String?,
  textIndex: json['textIndex'] as String?,
);

Map<String, dynamic> _$$EnquiryImplToJson(_$EnquiryImpl instance) => <String, dynamic>{
  'id': instance.id,
  'customerName': instance.customerName,
  'customerEmail': instance.customerEmail,
  'customerPhone': instance.customerPhone,
  'eventTypeValue': instance.eventType,
  'eventTypeLabel': instance.eventTypeLabel,
  'eventDate': instance.eventDate.toIso8601String(),
  'eventLocation': instance.eventLocation,
  'guestCount': instance.guestCount,
  'budgetRange': instance.budgetRange,
  'description': instance.description,
  'statusValue': instance.status,
  'statusLabel': instance.statusLabel,
  'paymentStatusValue': instance.paymentStatus,
  'paymentStatusLabel': instance.paymentStatusLabel,
  'totalCost': instance.totalCost,
  'advancePaid': instance.advancePaid,
  'assignedTo': instance.assignedTo,
  'createdAt': instance.createdAt.toIso8601String(),
  'updatedAt': instance.updatedAt?.toIso8601String(),
  'createdBy': instance.createdBy,
  'priorityValue': instance.priority,
  'priorityLabel': instance.priorityLabel,
  'sourceValue': instance.source,
  'sourceLabel': instance.sourceLabel,
  'notes': instance.notes,
  'images': instance.images,
  'customerNameLower': instance.customerNameLower,
  'phoneNormalized': instance.phoneNormalized,
  'assigneeName': instance.assigneeName,
  'createdByName': instance.createdByName,
  'statusUpdatedAt': instance.statusUpdatedAt?.toIso8601String(),
  'statusUpdatedBy': instance.statusUpdatedBy,
  'textIndex': instance.textIndex,
};
